### ISSUE TITLE
Testing against aiida development branch

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-plugin-cutter#21]
It would be nice to have an optional test against upcoming versions of aiida, in particular v1.
I tried this:

```yaml
    - TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="django" MOCK_EXECUTABLES=true

matrix:
  allow_failures:
    - env: TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="django" MOCK_EXECUTABLES=true

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install .[pre-commit,testing,docs]
- >
  if [[ ! -z "${AIIDA_BRANCH}" ]]; then
    cur_path="$(pwd)";
    cd ..;
    git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git;
    cd aiida_core;
    pip install -U .[testing];
    cd "$cur_path";
  fi
```

but I get an error when `pytest` tries to initiate (https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/421127367). 
Maybe a dependency version clash?
